--COMANDOS UTILIZANDO O DELETE

--DELETANDO UMA LINHA DA TABELA INCLUI
DELETE FROM inclui
    WHERE ID_pedido = 14 AND ID_servico = 2;

--DELETANDO UMA LINHA DA TABELA PEDIDO
DELETE FROM pedido
    WHERE ID_pedido = 14;

--DELETANDO UM TELEFONE DA TABELA TELEFONE
DELETE FROM telefone
    WHERE ID_telefone = 2;

--DELETANDO UM CLIENTE DA TABELA CLIENTES
DELETE FROM clientes
    WHERE CPF = '23456789012';